"""Added category column to items table

Revision ID: 21052f556dbc
Revises: 9e8102f051d0
Create Date: 2026-01-30 03:25:29.551974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21052f556dbc'
down_revision: Union[str, Sequence[str], None] = '9e8102f051d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('category', sa.String(), server_default='OTHER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'category')
    # ### end Alembic commands ###
