"""add_messageId_and_change_orderItem_columns

Revision ID: 4ed9c48cc6c6
Revises: efa75bb46ced
Create Date: 2026-01-26 11:08:46.349614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed9c48cc6c6'
down_revision: Union[str, Sequence[str], None] = 'efa75bb46ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_type', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('unit_type', sa.String(), nullable=True))
    op.drop_column('order_items', 'itemType')
    op.add_column('orders', sa.Column('message_id', sa.String(), nullable=True))
    op.drop_column('orders', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('orders', 'message_id')
    op.add_column('order_items', sa.Column('itemType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order_items', 'unit_type')
    op.drop_column('order_items', 'item_type')
    # ### end Alembic commands ###
