"""removed unnecessary fields from emails table

Revision ID: 68ffb0b171f0
Revises: a0b2085017e6
Create Date: 2026-01-27 12:38:48.765885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ffb0b171f0'
down_revision: Union[str, Sequence[str], None] = 'a0b2085017e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'isTransaction')
    op.drop_column('emails', 'isGeminiParsed')
    op.drop_column('emails', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('source', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('isGeminiParsed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('isTransaction', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
