"""add_foreign_key_to_transactions_userid

Revision ID: 6b079660a278
Revises: e0124e4f07ba
Create Date: 2026-01-09 12:45:49.646571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b079660a278'
down_revision: Union[str, Sequence[str], None] = 'e0124e4f07ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('userId', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'userId')
    # ### end Alembic commands ###
