"""added gmail token to users

Revision ID: 8cac8cc339e3
Revises: 6b079660a278
Create Date: 2026-01-10 01:46:41.311299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cac8cc339e3'
down_revision: Union[str, Sequence[str], None] = '6b079660a278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmailRefreshToken', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gmailRefreshTokenCreatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmailRefreshTokenCreatedAt')
    op.drop_column('users', 'gmailRefreshToken')
    # ### end Alembic commands ###
