"""make order_id unique

Revision ID: a0b2085017e6
Revises: 4ed9c48cc6c6
Create Date: 2026-01-26 11:16:39.405668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b2085017e6'
down_revision: Union[str, Sequence[str], None] = '4ed9c48cc6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'orders', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    # ### end Alembic commands ###
