"""added_accountId_to_emails_and_transactions

Revision ID: a284a4453838
Revises: e83094c11a24
Create Date: 2026-01-22 05:43:23.731030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a284a4453838'
down_revision: Union[str, Sequence[str], None] = 'e83094c11a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('accountId', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'emails', 'accounts', ['accountId'], ['id'])
    op.add_column('transactions', sa.Column('accountId', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'accounts', ['accountId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'accountId')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'accountId')
    # ### end Alembic commands ###
