"""replaced transaction field for analytics flag

Revision ID: ada78171bc44
Revises: 68ffb0b171f0
Create Date: 2026-01-27 14:11:09.509051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada78171bc44'
down_revision: Union[str, Sequence[str], None] = '68ffb0b171f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_include_analytics', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.drop_column('transactions', 'source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('source_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'is_include_analytics')
    # ### end Alembic commands ###
