"""added_new_table_accounnts

Revision ID: b3204402824b
Revises: 9336f4c59b9c
Create Date: 2026-01-19 22:28:20.083344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3204402824b'
down_revision: Union[str, Sequence[str], None] = '9336f4c59b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('gmailRefreshToken', sa.String(), nullable=True),
    sa.Column('gmailRefreshTokenCreatedAt', sa.DateTime(), nullable=True),
    sa.Column('isSyncing', sa.Boolean(), nullable=False),
    sa.Column('lastSyncedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.drop_column('users', 'gmailRefreshTokenCreatedAt')
    op.drop_column('users', 'lastSyncedAt')
    op.drop_column('users', 'isSyncing')
    op.drop_column('users', 'gmailRefreshToken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmailRefreshToken', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('isSyncing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastSyncedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gmailRefreshTokenCreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
