"""Initial migration

Revision ID: b4c2c9a07ee3
Revises: 
Create Date: 2026-01-06 17:33:28.053114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4c2c9a07ee3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the moneybhai schema first
    op.execute("CREATE SCHEMA IF NOT EXISTS moneybhai")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('emailSender', sa.String(length=128), nullable=True),
    sa.Column('emailId', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('isTransaction', sa.Boolean(), nullable=True),
    sa.Column('isGeminiParsed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='moneybhai'
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=128), nullable=True),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('source_type', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=128), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('emailSender', sa.String(length=128), nullable=True),
    sa.Column('emailId', sa.String(length=128), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='moneybhai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions', schema='moneybhai')
    op.drop_table('emails', schema='moneybhai')
    
    # Drop the moneybhai schema (will fail if other objects exist)
    op.execute("DROP SCHEMA IF EXISTS moneybhai")
    # ### end Alembic commands ###
