"""udpate_to_latest_changes

Revision ID: e0124e4f07ba
Revises: b4c2c9a07ee3
Create Date: 2026-01-09 12:42:44.550800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0124e4f07ba'
down_revision: Union[str, Sequence[str], None] = 'b4c2c9a07ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('emailSender', sa.String(length=128), nullable=True),
    sa.Column('emailId', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('isTransaction', sa.Boolean(), nullable=True),
    sa.Column('isGeminiParsed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=128), nullable=True),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('source_type', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=128), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('emailSender', sa.String(length=128), nullable=True),
    sa.Column('emailId', sa.String(length=128), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('emails')
    # ### end Alembic commands ###
