"""added_emailId_column_to_accounts_table

Revision ID: e83094c11a24
Revises: b3204402824b
Create Date: 2026-01-20 00:55:25.949633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83094c11a24'
down_revision: Union[str, Sequence[str], None] = 'b3204402824b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('emailId', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'emailId')
    # ### end Alembic commands ###
