"""added_analytics_column_to_users_table

Revision ID: ed203b6be420
Revises: a284a4453838
Create Date: 2026-01-23 18:31:57.935040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed203b6be420'
down_revision: Union[str, Sequence[str], None] = 'a284a4453838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_allowed_analytics', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_allowed_analytics')
    # ### end Alembic commands ###
