"""converted_type_to_itemType

Revision ID: efa75bb46ced
Revises: ed43f890bd75
Create Date: 2026-01-24 11:41:06.981017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa75bb46ced'
down_revision: Union[str, Sequence[str], None] = 'ed43f890bd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('itemType', sa.String(), nullable=True))
    op.drop_column('order_items', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order_items', 'itemType')
    # ### end Alembic commands ###
